apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    mon: prometheus-kube-system
  name: cilium-agent
  namespace: kube-system
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: cilium